logging:
  level:
    com.ub: debug
server:
  port: 8080

com:
  ub:
    beer-inventory-service-host: http://localhost:8082

spring:
  datasource:
    initialization-mode: embedded
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true
  cache:
    jcache:
      config: classpath:ehcache.xml